import { Amplify } from 'aws-amplify';
import amplifyOutputs from '../amplify_outputs.json';

/**
 * Configure AWS Amplify with backend outputs
 *
 * This file imports the amplify_outputs.json generated by the Amplify CLI
 * and configures the Amplify client for authentication, API, and storage.
 */

Amplify.configure(amplifyOutputs);

export default Amplify;
