/* tslint:disable */
/* eslint-disable */
//  This file was automatically generated and should not be edited.

export type Business = {
  __typename: "Business",
  address: string,
  billingType?: BusinessBillingType | null,
  businessType?: BusinessBusinessType | null,
  city: string,
  cpmRate?: number | null,
  createdAt: string,
  currentSpend?: number | null,
  description?: string | null,
  email: string,
  id: string,
  isActive?: boolean | null,
  isVerified?: boolean | null,
  latitude?: number | null,
  logoKey?: string | null,
  logoUrl?: string | null,
  longitude?: number | null,
  monthlyBudget?: number | null,
  name: string,
  owner: string,
  phone?: string | null,
  rejectionReason?: string | null,
  rewards?: ModelRewardConnection | null,
  serviceRadius?: number | null,
  state: string,
  updatedAt: string,
  verificationStatus?: BusinessVerificationStatus | null,
  website?: string | null,
  zipCode: string,
};

export enum BusinessBillingType {
  CPC = "CPC",
  CPM = "CPM",
  MONTHLY_RETAINER = "MONTHLY_RETAINER",
}


export enum BusinessBusinessType {
  EDUCATION = "EDUCATION",
  ENTERTAINMENT = "ENTERTAINMENT",
  OTHER = "OTHER",
  RESTAURANT = "RESTAURANT",
  RETAIL = "RETAIL",
  SERVICES = "SERVICES",
  SPORTS_RECREATION = "SPORTS_RECREATION",
}


export type ModelRewardConnection = {
  __typename: "ModelRewardConnection",
  items:  Array<Reward | null >,
  nextToken?: string | null,
};

export type Reward = {
  __typename: "Reward",
  availableRadius?: number | null,
  business?: Business | null,
  businessId: string,
  category?: RewardCategory | null,
  clicks?: number | null,
  createdAt: string,
  currentRedemptions?: number | null,
  dailyLimit?: number | null,
  daysOfWeek?: Array< string | null > | null,
  description: string,
  endDate?: string | null,
  id: string,
  imageKey?: string | null,
  imageUrl?: string | null,
  impressions?: number | null,
  isActive?: boolean | null,
  owner?: string | null,
  pointCost: number,
  redemptionInstructions?: string | null,
  redemptionRecords?: ModelRewardRedemptionConnection | null,
  redemptionType?: RewardRedemptionType | null,
  redemptions?: number | null,
  retailValue?: number | null,
  rewardType?: RewardRewardType | null,
  startDate: string,
  status?: RewardStatus | null,
  targetAgeRanges?: Array< string | null > | null,
  targetFamilySizes?: Array< number | null > | null,
  termsAndConditions?: string | null,
  title: string,
  totalAvailable?: number | null,
  updatedAt: string,
};

export enum RewardCategory {
  ARTS_CRAFTS = "ARTS_CRAFTS",
  EDUCATION = "EDUCATION",
  ENTERTAINMENT = "ENTERTAINMENT",
  FAMILY_ACTIVITY = "FAMILY_ACTIVITY",
  FOOD = "FOOD",
  SPORTS = "SPORTS",
  TECHNOLOGY = "TECHNOLOGY",
}


export type ModelRewardRedemptionConnection = {
  __typename: "ModelRewardRedemptionConnection",
  items:  Array<RewardRedemption | null >,
  nextToken?: string | null,
};

export type RewardRedemption = {
  __typename: "RewardRedemption",
  businessId?: string | null,
  businessRevenue?: number | null,
  childAge?: number | null,
  childId: string,
  createdAt: string,
  expiresAt?: string | null,
  familyId: string,
  fulfilledAt?: string | null,
  id: string,
  notes?: string | null,
  owner?: string | null,
  pointsSpent: number,
  redemptionCity?: string | null,
  redemptionCode?: string | null,
  redemptionDate?: string | null,
  redemptionStatus?: RewardRedemptionRedemptionStatus | null,
  redemptionZip?: string | null,
  reward?: Reward | null,
  rewardId: string,
  updatedAt: string,
};

export enum RewardRedemptionRedemptionStatus {
  APPROVED = "APPROVED",
  CANCELLED = "CANCELLED",
  EXPIRED = "EXPIRED",
  PENDING = "PENDING",
  REDEEMED = "REDEEMED",
}


export enum RewardRedemptionType {
  CODE = "CODE",
  IN_STORE = "IN_STORE",
  ONLINE = "ONLINE",
  QR_CODE = "QR_CODE",
}


export enum RewardRewardType {
  DIGITAL_CONTENT = "DIGITAL_CONTENT",
  EXPERIENCE = "EXPERIENCE",
  FAMILY_ACTIVITY = "FAMILY_ACTIVITY",
  FOOD = "FOOD",
  PHYSICAL_ITEM = "PHYSICAL_ITEM",
  SERVICE = "SERVICE",
}


export enum RewardStatus {
  ACTIVE = "ACTIVE",
  APPROVED = "APPROVED",
  COMPLETED = "COMPLETED",
  DRAFT = "DRAFT",
  PAUSED = "PAUSED",
  PENDING_APPROVAL = "PENDING_APPROVAL",
}


export enum BusinessVerificationStatus {
  APPROVED = "APPROVED",
  PENDING = "PENDING",
  REJECTED = "REJECTED",
}


export type BusinessAnalytics = {
  __typename: "BusinessAnalytics",
  avgChildAge?: number | null,
  businessId: string,
  clicks?: number | null,
  createdAt: string,
  date: string,
  id: string,
  impressions?: number | null,
  owner?: string | null,
  redemptions?: number | null,
  revenue?: number | null,
  spend?: number | null,
  topRewardId?: string | null,
  updatedAt: string,
};

export type ModelBusinessAnalyticsFilterInput = {
  and?: Array< ModelBusinessAnalyticsFilterInput | null > | null,
  avgChildAge?: ModelFloatInput | null,
  businessId?: ModelIDInput | null,
  clicks?: ModelIntInput | null,
  createdAt?: ModelStringInput | null,
  date?: ModelStringInput | null,
  id?: ModelIDInput | null,
  impressions?: ModelIntInput | null,
  not?: ModelBusinessAnalyticsFilterInput | null,
  or?: Array< ModelBusinessAnalyticsFilterInput | null > | null,
  owner?: ModelStringInput | null,
  redemptions?: ModelIntInput | null,
  revenue?: ModelFloatInput | null,
  spend?: ModelFloatInput | null,
  topRewardId?: ModelStringInput | null,
  updatedAt?: ModelStringInput | null,
};

export type ModelFloatInput = {
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  between?: Array< number | null > | null,
  eq?: number | null,
  ge?: number | null,
  gt?: number | null,
  le?: number | null,
  lt?: number | null,
  ne?: number | null,
};

export enum ModelAttributeTypes {
  _null = "_null",
  binary = "binary",
  binarySet = "binarySet",
  bool = "bool",
  list = "list",
  map = "map",
  number = "number",
  numberSet = "numberSet",
  string = "string",
  stringSet = "stringSet",
}


export type ModelIDInput = {
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  beginsWith?: string | null,
  between?: Array< string | null > | null,
  contains?: string | null,
  eq?: string | null,
  ge?: string | null,
  gt?: string | null,
  le?: string | null,
  lt?: string | null,
  ne?: string | null,
  notContains?: string | null,
  size?: ModelSizeInput | null,
};

export type ModelSizeInput = {
  between?: Array< number | null > | null,
  eq?: number | null,
  ge?: number | null,
  gt?: number | null,
  le?: number | null,
  lt?: number | null,
  ne?: number | null,
};

export type ModelIntInput = {
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  between?: Array< number | null > | null,
  eq?: number | null,
  ge?: number | null,
  gt?: number | null,
  le?: number | null,
  lt?: number | null,
  ne?: number | null,
};

export type ModelStringInput = {
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  beginsWith?: string | null,
  between?: Array< string | null > | null,
  contains?: string | null,
  eq?: string | null,
  ge?: string | null,
  gt?: string | null,
  le?: string | null,
  lt?: string | null,
  ne?: string | null,
  notContains?: string | null,
  size?: ModelSizeInput | null,
};

export type ModelBusinessAnalyticsConnection = {
  __typename: "ModelBusinessAnalyticsConnection",
  items:  Array<BusinessAnalytics | null >,
  nextToken?: string | null,
};

export type ModelBusinessFilterInput = {
  address?: ModelStringInput | null,
  and?: Array< ModelBusinessFilterInput | null > | null,
  billingType?: ModelBusinessBillingTypeInput | null,
  businessType?: ModelBusinessBusinessTypeInput | null,
  city?: ModelStringInput | null,
  cpmRate?: ModelFloatInput | null,
  createdAt?: ModelStringInput | null,
  currentSpend?: ModelFloatInput | null,
  description?: ModelStringInput | null,
  email?: ModelStringInput | null,
  id?: ModelIDInput | null,
  isActive?: ModelBooleanInput | null,
  isVerified?: ModelBooleanInput | null,
  latitude?: ModelFloatInput | null,
  logoKey?: ModelStringInput | null,
  logoUrl?: ModelStringInput | null,
  longitude?: ModelFloatInput | null,
  monthlyBudget?: ModelFloatInput | null,
  name?: ModelStringInput | null,
  not?: ModelBusinessFilterInput | null,
  or?: Array< ModelBusinessFilterInput | null > | null,
  owner?: ModelStringInput | null,
  phone?: ModelStringInput | null,
  rejectionReason?: ModelStringInput | null,
  serviceRadius?: ModelFloatInput | null,
  state?: ModelStringInput | null,
  updatedAt?: ModelStringInput | null,
  verificationStatus?: ModelBusinessVerificationStatusInput | null,
  website?: ModelStringInput | null,
  zipCode?: ModelStringInput | null,
};

export type ModelBusinessBillingTypeInput = {
  eq?: BusinessBillingType | null,
  ne?: BusinessBillingType | null,
};

export type ModelBusinessBusinessTypeInput = {
  eq?: BusinessBusinessType | null,
  ne?: BusinessBusinessType | null,
};

export type ModelBooleanInput = {
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  eq?: boolean | null,
  ne?: boolean | null,
};

export type ModelBusinessVerificationStatusInput = {
  eq?: BusinessVerificationStatus | null,
  ne?: BusinessVerificationStatus | null,
};

export type ModelBusinessConnection = {
  __typename: "ModelBusinessConnection",
  items:  Array<Business | null >,
  nextToken?: string | null,
};

export type ModelRewardRedemptionFilterInput = {
  and?: Array< ModelRewardRedemptionFilterInput | null > | null,
  businessId?: ModelStringInput | null,
  businessRevenue?: ModelFloatInput | null,
  childAge?: ModelIntInput | null,
  childId?: ModelStringInput | null,
  createdAt?: ModelStringInput | null,
  expiresAt?: ModelStringInput | null,
  familyId?: ModelStringInput | null,
  fulfilledAt?: ModelStringInput | null,
  id?: ModelIDInput | null,
  not?: ModelRewardRedemptionFilterInput | null,
  notes?: ModelStringInput | null,
  or?: Array< ModelRewardRedemptionFilterInput | null > | null,
  owner?: ModelStringInput | null,
  pointsSpent?: ModelIntInput | null,
  redemptionCity?: ModelStringInput | null,
  redemptionCode?: ModelStringInput | null,
  redemptionDate?: ModelStringInput | null,
  redemptionStatus?: ModelRewardRedemptionRedemptionStatusInput | null,
  redemptionZip?: ModelStringInput | null,
  rewardId?: ModelIDInput | null,
  updatedAt?: ModelStringInput | null,
};

export type ModelRewardRedemptionRedemptionStatusInput = {
  eq?: RewardRedemptionRedemptionStatus | null,
  ne?: RewardRedemptionRedemptionStatus | null,
};

export type ModelRewardFilterInput = {
  and?: Array< ModelRewardFilterInput | null > | null,
  availableRadius?: ModelFloatInput | null,
  businessId?: ModelIDInput | null,
  category?: ModelRewardCategoryInput | null,
  clicks?: ModelIntInput | null,
  createdAt?: ModelStringInput | null,
  currentRedemptions?: ModelIntInput | null,
  dailyLimit?: ModelIntInput | null,
  daysOfWeek?: ModelStringInput | null,
  description?: ModelStringInput | null,
  endDate?: ModelStringInput | null,
  id?: ModelIDInput | null,
  imageKey?: ModelStringInput | null,
  imageUrl?: ModelStringInput | null,
  impressions?: ModelIntInput | null,
  isActive?: ModelBooleanInput | null,
  not?: ModelRewardFilterInput | null,
  or?: Array< ModelRewardFilterInput | null > | null,
  owner?: ModelStringInput | null,
  pointCost?: ModelIntInput | null,
  redemptionInstructions?: ModelStringInput | null,
  redemptionType?: ModelRewardRedemptionTypeInput | null,
  redemptions?: ModelIntInput | null,
  retailValue?: ModelFloatInput | null,
  rewardType?: ModelRewardRewardTypeInput | null,
  startDate?: ModelStringInput | null,
  status?: ModelRewardStatusInput | null,
  targetAgeRanges?: ModelStringInput | null,
  targetFamilySizes?: ModelIntInput | null,
  termsAndConditions?: ModelStringInput | null,
  title?: ModelStringInput | null,
  totalAvailable?: ModelIntInput | null,
  updatedAt?: ModelStringInput | null,
};

export type ModelRewardCategoryInput = {
  eq?: RewardCategory | null,
  ne?: RewardCategory | null,
};

export type ModelRewardRedemptionTypeInput = {
  eq?: RewardRedemptionType | null,
  ne?: RewardRedemptionType | null,
};

export type ModelRewardRewardTypeInput = {
  eq?: RewardRewardType | null,
  ne?: RewardRewardType | null,
};

export type ModelRewardStatusInput = {
  eq?: RewardStatus | null,
  ne?: RewardStatus | null,
};

export type ModelBusinessConditionInput = {
  address?: ModelStringInput | null,
  and?: Array< ModelBusinessConditionInput | null > | null,
  billingType?: ModelBusinessBillingTypeInput | null,
  businessType?: ModelBusinessBusinessTypeInput | null,
  city?: ModelStringInput | null,
  cpmRate?: ModelFloatInput | null,
  createdAt?: ModelStringInput | null,
  currentSpend?: ModelFloatInput | null,
  description?: ModelStringInput | null,
  email?: ModelStringInput | null,
  isActive?: ModelBooleanInput | null,
  isVerified?: ModelBooleanInput | null,
  latitude?: ModelFloatInput | null,
  logoKey?: ModelStringInput | null,
  logoUrl?: ModelStringInput | null,
  longitude?: ModelFloatInput | null,
  monthlyBudget?: ModelFloatInput | null,
  name?: ModelStringInput | null,
  not?: ModelBusinessConditionInput | null,
  or?: Array< ModelBusinessConditionInput | null > | null,
  owner?: ModelStringInput | null,
  phone?: ModelStringInput | null,
  rejectionReason?: ModelStringInput | null,
  serviceRadius?: ModelFloatInput | null,
  state?: ModelStringInput | null,
  updatedAt?: ModelStringInput | null,
  verificationStatus?: ModelBusinessVerificationStatusInput | null,
  website?: ModelStringInput | null,
  zipCode?: ModelStringInput | null,
};

export type CreateBusinessInput = {
  address: string,
  billingType?: BusinessBillingType | null,
  businessType?: BusinessBusinessType | null,
  city: string,
  cpmRate?: number | null,
  currentSpend?: number | null,
  description?: string | null,
  email: string,
  id?: string | null,
  isActive?: boolean | null,
  isVerified?: boolean | null,
  latitude?: number | null,
  logoKey?: string | null,
  logoUrl?: string | null,
  longitude?: number | null,
  monthlyBudget?: number | null,
  name: string,
  owner: string,
  phone?: string | null,
  rejectionReason?: string | null,
  serviceRadius?: number | null,
  state: string,
  verificationStatus?: BusinessVerificationStatus | null,
  website?: string | null,
  zipCode: string,
};

export type ModelBusinessAnalyticsConditionInput = {
  and?: Array< ModelBusinessAnalyticsConditionInput | null > | null,
  avgChildAge?: ModelFloatInput | null,
  businessId?: ModelIDInput | null,
  clicks?: ModelIntInput | null,
  createdAt?: ModelStringInput | null,
  date?: ModelStringInput | null,
  impressions?: ModelIntInput | null,
  not?: ModelBusinessAnalyticsConditionInput | null,
  or?: Array< ModelBusinessAnalyticsConditionInput | null > | null,
  owner?: ModelStringInput | null,
  redemptions?: ModelIntInput | null,
  revenue?: ModelFloatInput | null,
  spend?: ModelFloatInput | null,
  topRewardId?: ModelStringInput | null,
  updatedAt?: ModelStringInput | null,
};

export type CreateBusinessAnalyticsInput = {
  avgChildAge?: number | null,
  businessId: string,
  clicks?: number | null,
  date: string,
  id?: string | null,
  impressions?: number | null,
  redemptions?: number | null,
  revenue?: number | null,
  spend?: number | null,
  topRewardId?: string | null,
};

export type ModelRewardConditionInput = {
  and?: Array< ModelRewardConditionInput | null > | null,
  availableRadius?: ModelFloatInput | null,
  businessId?: ModelIDInput | null,
  category?: ModelRewardCategoryInput | null,
  clicks?: ModelIntInput | null,
  createdAt?: ModelStringInput | null,
  currentRedemptions?: ModelIntInput | null,
  dailyLimit?: ModelIntInput | null,
  daysOfWeek?: ModelStringInput | null,
  description?: ModelStringInput | null,
  endDate?: ModelStringInput | null,
  imageKey?: ModelStringInput | null,
  imageUrl?: ModelStringInput | null,
  impressions?: ModelIntInput | null,
  isActive?: ModelBooleanInput | null,
  not?: ModelRewardConditionInput | null,
  or?: Array< ModelRewardConditionInput | null > | null,
  owner?: ModelStringInput | null,
  pointCost?: ModelIntInput | null,
  redemptionInstructions?: ModelStringInput | null,
  redemptionType?: ModelRewardRedemptionTypeInput | null,
  redemptions?: ModelIntInput | null,
  retailValue?: ModelFloatInput | null,
  rewardType?: ModelRewardRewardTypeInput | null,
  startDate?: ModelStringInput | null,
  status?: ModelRewardStatusInput | null,
  targetAgeRanges?: ModelStringInput | null,
  targetFamilySizes?: ModelIntInput | null,
  termsAndConditions?: ModelStringInput | null,
  title?: ModelStringInput | null,
  totalAvailable?: ModelIntInput | null,
  updatedAt?: ModelStringInput | null,
};

export type CreateRewardInput = {
  availableRadius?: number | null,
  businessId: string,
  category?: RewardCategory | null,
  clicks?: number | null,
  currentRedemptions?: number | null,
  dailyLimit?: number | null,
  daysOfWeek?: Array< string | null > | null,
  description: string,
  endDate?: string | null,
  id?: string | null,
  imageKey?: string | null,
  imageUrl?: string | null,
  impressions?: number | null,
  isActive?: boolean | null,
  pointCost: number,
  redemptionInstructions?: string | null,
  redemptionType?: RewardRedemptionType | null,
  redemptions?: number | null,
  retailValue?: number | null,
  rewardType?: RewardRewardType | null,
  startDate: string,
  status?: RewardStatus | null,
  targetAgeRanges?: Array< string | null > | null,
  targetFamilySizes?: Array< number | null > | null,
  termsAndConditions?: string | null,
  title: string,
  totalAvailable?: number | null,
};

export type ModelRewardRedemptionConditionInput = {
  and?: Array< ModelRewardRedemptionConditionInput | null > | null,
  businessId?: ModelStringInput | null,
  businessRevenue?: ModelFloatInput | null,
  childAge?: ModelIntInput | null,
  childId?: ModelStringInput | null,
  createdAt?: ModelStringInput | null,
  expiresAt?: ModelStringInput | null,
  familyId?: ModelStringInput | null,
  fulfilledAt?: ModelStringInput | null,
  not?: ModelRewardRedemptionConditionInput | null,
  notes?: ModelStringInput | null,
  or?: Array< ModelRewardRedemptionConditionInput | null > | null,
  owner?: ModelStringInput | null,
  pointsSpent?: ModelIntInput | null,
  redemptionCity?: ModelStringInput | null,
  redemptionCode?: ModelStringInput | null,
  redemptionDate?: ModelStringInput | null,
  redemptionStatus?: ModelRewardRedemptionRedemptionStatusInput | null,
  redemptionZip?: ModelStringInput | null,
  rewardId?: ModelIDInput | null,
  updatedAt?: ModelStringInput | null,
};

export type CreateRewardRedemptionInput = {
  businessId?: string | null,
  businessRevenue?: number | null,
  childAge?: number | null,
  childId: string,
  expiresAt?: string | null,
  familyId: string,
  fulfilledAt?: string | null,
  id?: string | null,
  notes?: string | null,
  pointsSpent: number,
  redemptionCity?: string | null,
  redemptionCode?: string | null,
  redemptionDate?: string | null,
  redemptionStatus?: RewardRedemptionRedemptionStatus | null,
  redemptionZip?: string | null,
  rewardId: string,
};

export type DeleteBusinessInput = {
  id: string,
};

export type DeleteBusinessAnalyticsInput = {
  id: string,
};

export type DeleteRewardInput = {
  id: string,
};

export type DeleteRewardRedemptionInput = {
  id: string,
};

export type UpdateBusinessInput = {
  address?: string | null,
  billingType?: BusinessBillingType | null,
  businessType?: BusinessBusinessType | null,
  city?: string | null,
  cpmRate?: number | null,
  currentSpend?: number | null,
  description?: string | null,
  email?: string | null,
  id: string,
  isActive?: boolean | null,
  isVerified?: boolean | null,
  latitude?: number | null,
  logoKey?: string | null,
  logoUrl?: string | null,
  longitude?: number | null,
  monthlyBudget?: number | null,
  name?: string | null,
  owner?: string | null,
  phone?: string | null,
  rejectionReason?: string | null,
  serviceRadius?: number | null,
  state?: string | null,
  verificationStatus?: BusinessVerificationStatus | null,
  website?: string | null,
  zipCode?: string | null,
};

export type UpdateBusinessAnalyticsInput = {
  avgChildAge?: number | null,
  businessId?: string | null,
  clicks?: number | null,
  date?: string | null,
  id: string,
  impressions?: number | null,
  redemptions?: number | null,
  revenue?: number | null,
  spend?: number | null,
  topRewardId?: string | null,
};

export type UpdateRewardInput = {
  availableRadius?: number | null,
  businessId?: string | null,
  category?: RewardCategory | null,
  clicks?: number | null,
  currentRedemptions?: number | null,
  dailyLimit?: number | null,
  daysOfWeek?: Array< string | null > | null,
  description?: string | null,
  endDate?: string | null,
  id: string,
  imageKey?: string | null,
  imageUrl?: string | null,
  impressions?: number | null,
  isActive?: boolean | null,
  pointCost?: number | null,
  redemptionInstructions?: string | null,
  redemptionType?: RewardRedemptionType | null,
  redemptions?: number | null,
  retailValue?: number | null,
  rewardType?: RewardRewardType | null,
  startDate?: string | null,
  status?: RewardStatus | null,
  targetAgeRanges?: Array< string | null > | null,
  targetFamilySizes?: Array< number | null > | null,
  termsAndConditions?: string | null,
  title?: string | null,
  totalAvailable?: number | null,
};

export type UpdateRewardRedemptionInput = {
  businessId?: string | null,
  businessRevenue?: number | null,
  childAge?: number | null,
  childId?: string | null,
  expiresAt?: string | null,
  familyId?: string | null,
  fulfilledAt?: string | null,
  id: string,
  notes?: string | null,
  pointsSpent?: number | null,
  redemptionCity?: string | null,
  redemptionCode?: string | null,
  redemptionDate?: string | null,
  redemptionStatus?: RewardRedemptionRedemptionStatus | null,
  redemptionZip?: string | null,
  rewardId?: string | null,
};

export type ModelSubscriptionBusinessFilterInput = {
  address?: ModelSubscriptionStringInput | null,
  and?: Array< ModelSubscriptionBusinessFilterInput | null > | null,
  billingType?: ModelSubscriptionStringInput | null,
  businessType?: ModelSubscriptionStringInput | null,
  city?: ModelSubscriptionStringInput | null,
  cpmRate?: ModelSubscriptionFloatInput | null,
  createdAt?: ModelSubscriptionStringInput | null,
  currentSpend?: ModelSubscriptionFloatInput | null,
  description?: ModelSubscriptionStringInput | null,
  email?: ModelSubscriptionStringInput | null,
  id?: ModelSubscriptionIDInput | null,
  isActive?: ModelSubscriptionBooleanInput | null,
  isVerified?: ModelSubscriptionBooleanInput | null,
  latitude?: ModelSubscriptionFloatInput | null,
  logoKey?: ModelSubscriptionStringInput | null,
  logoUrl?: ModelSubscriptionStringInput | null,
  longitude?: ModelSubscriptionFloatInput | null,
  monthlyBudget?: ModelSubscriptionFloatInput | null,
  name?: ModelSubscriptionStringInput | null,
  or?: Array< ModelSubscriptionBusinessFilterInput | null > | null,
  owner?: ModelStringInput | null,
  phone?: ModelSubscriptionStringInput | null,
  rejectionReason?: ModelSubscriptionStringInput | null,
  serviceRadius?: ModelSubscriptionFloatInput | null,
  state?: ModelSubscriptionStringInput | null,
  updatedAt?: ModelSubscriptionStringInput | null,
  verificationStatus?: ModelSubscriptionStringInput | null,
  website?: ModelSubscriptionStringInput | null,
  zipCode?: ModelSubscriptionStringInput | null,
};

export type ModelSubscriptionStringInput = {
  beginsWith?: string | null,
  between?: Array< string | null > | null,
  contains?: string | null,
  eq?: string | null,
  ge?: string | null,
  gt?: string | null,
  in?: Array< string | null > | null,
  le?: string | null,
  lt?: string | null,
  ne?: string | null,
  notContains?: string | null,
  notIn?: Array< string | null > | null,
};

export type ModelSubscriptionFloatInput = {
  between?: Array< number | null > | null,
  eq?: number | null,
  ge?: number | null,
  gt?: number | null,
  in?: Array< number | null > | null,
  le?: number | null,
  lt?: number | null,
  ne?: number | null,
  notIn?: Array< number | null > | null,
};

export type ModelSubscriptionIDInput = {
  beginsWith?: string | null,
  between?: Array< string | null > | null,
  contains?: string | null,
  eq?: string | null,
  ge?: string | null,
  gt?: string | null,
  in?: Array< string | null > | null,
  le?: string | null,
  lt?: string | null,
  ne?: string | null,
  notContains?: string | null,
  notIn?: Array< string | null > | null,
};

export type ModelSubscriptionBooleanInput = {
  eq?: boolean | null,
  ne?: boolean | null,
};

export type ModelSubscriptionBusinessAnalyticsFilterInput = {
  and?: Array< ModelSubscriptionBusinessAnalyticsFilterInput | null > | null,
  avgChildAge?: ModelSubscriptionFloatInput | null,
  businessId?: ModelSubscriptionIDInput | null,
  clicks?: ModelSubscriptionIntInput | null,
  createdAt?: ModelSubscriptionStringInput | null,
  date?: ModelSubscriptionStringInput | null,
  id?: ModelSubscriptionIDInput | null,
  impressions?: ModelSubscriptionIntInput | null,
  or?: Array< ModelSubscriptionBusinessAnalyticsFilterInput | null > | null,
  owner?: ModelStringInput | null,
  redemptions?: ModelSubscriptionIntInput | null,
  revenue?: ModelSubscriptionFloatInput | null,
  spend?: ModelSubscriptionFloatInput | null,
  topRewardId?: ModelSubscriptionStringInput | null,
  updatedAt?: ModelSubscriptionStringInput | null,
};

export type ModelSubscriptionIntInput = {
  between?: Array< number | null > | null,
  eq?: number | null,
  ge?: number | null,
  gt?: number | null,
  in?: Array< number | null > | null,
  le?: number | null,
  lt?: number | null,
  ne?: number | null,
  notIn?: Array< number | null > | null,
};

export type ModelSubscriptionRewardFilterInput = {
  and?: Array< ModelSubscriptionRewardFilterInput | null > | null,
  availableRadius?: ModelSubscriptionFloatInput | null,
  businessId?: ModelSubscriptionIDInput | null,
  category?: ModelSubscriptionStringInput | null,
  clicks?: ModelSubscriptionIntInput | null,
  createdAt?: ModelSubscriptionStringInput | null,
  currentRedemptions?: ModelSubscriptionIntInput | null,
  dailyLimit?: ModelSubscriptionIntInput | null,
  daysOfWeek?: ModelSubscriptionStringInput | null,
  description?: ModelSubscriptionStringInput | null,
  endDate?: ModelSubscriptionStringInput | null,
  id?: ModelSubscriptionIDInput | null,
  imageKey?: ModelSubscriptionStringInput | null,
  imageUrl?: ModelSubscriptionStringInput | null,
  impressions?: ModelSubscriptionIntInput | null,
  isActive?: ModelSubscriptionBooleanInput | null,
  or?: Array< ModelSubscriptionRewardFilterInput | null > | null,
  owner?: ModelStringInput | null,
  pointCost?: ModelSubscriptionIntInput | null,
  redemptionInstructions?: ModelSubscriptionStringInput | null,
  redemptionType?: ModelSubscriptionStringInput | null,
  redemptions?: ModelSubscriptionIntInput | null,
  retailValue?: ModelSubscriptionFloatInput | null,
  rewardType?: ModelSubscriptionStringInput | null,
  startDate?: ModelSubscriptionStringInput | null,
  status?: ModelSubscriptionStringInput | null,
  targetAgeRanges?: ModelSubscriptionStringInput | null,
  targetFamilySizes?: ModelSubscriptionIntInput | null,
  termsAndConditions?: ModelSubscriptionStringInput | null,
  title?: ModelSubscriptionStringInput | null,
  totalAvailable?: ModelSubscriptionIntInput | null,
  updatedAt?: ModelSubscriptionStringInput | null,
};

export type ModelSubscriptionRewardRedemptionFilterInput = {
  and?: Array< ModelSubscriptionRewardRedemptionFilterInput | null > | null,
  businessId?: ModelSubscriptionStringInput | null,
  businessRevenue?: ModelSubscriptionFloatInput | null,
  childAge?: ModelSubscriptionIntInput | null,
  childId?: ModelSubscriptionStringInput | null,
  createdAt?: ModelSubscriptionStringInput | null,
  expiresAt?: ModelSubscriptionStringInput | null,
  familyId?: ModelSubscriptionStringInput | null,
  fulfilledAt?: ModelSubscriptionStringInput | null,
  id?: ModelSubscriptionIDInput | null,
  notes?: ModelSubscriptionStringInput | null,
  or?: Array< ModelSubscriptionRewardRedemptionFilterInput | null > | null,
  owner?: ModelStringInput | null,
  pointsSpent?: ModelSubscriptionIntInput | null,
  redemptionCity?: ModelSubscriptionStringInput | null,
  redemptionCode?: ModelSubscriptionStringInput | null,
  redemptionDate?: ModelSubscriptionStringInput | null,
  redemptionStatus?: ModelSubscriptionStringInput | null,
  redemptionZip?: ModelSubscriptionStringInput | null,
  rewardId?: ModelSubscriptionIDInput | null,
  updatedAt?: ModelSubscriptionStringInput | null,
};

export type GetBusinessQueryVariables = {
  id: string,
};

export type GetBusinessQuery = {
  getBusiness?:  {
    __typename: "Business",
    address: string,
    billingType?: BusinessBillingType | null,
    businessType?: BusinessBusinessType | null,
    city: string,
    cpmRate?: number | null,
    createdAt: string,
    currentSpend?: number | null,
    description?: string | null,
    email: string,
    id: string,
    isActive?: boolean | null,
    isVerified?: boolean | null,
    latitude?: number | null,
    logoKey?: string | null,
    logoUrl?: string | null,
    longitude?: number | null,
    monthlyBudget?: number | null,
    name: string,
    owner: string,
    phone?: string | null,
    rejectionReason?: string | null,
    rewards?:  {
      __typename: "ModelRewardConnection",
      nextToken?: string | null,
    } | null,
    serviceRadius?: number | null,
    state: string,
    updatedAt: string,
    verificationStatus?: BusinessVerificationStatus | null,
    website?: string | null,
    zipCode: string,
  } | null,
};

export type GetBusinessAnalyticsQueryVariables = {
  id: string,
};

export type GetBusinessAnalyticsQuery = {
  getBusinessAnalytics?:  {
    __typename: "BusinessAnalytics",
    avgChildAge?: number | null,
    businessId: string,
    clicks?: number | null,
    createdAt: string,
    date: string,
    id: string,
    impressions?: number | null,
    owner?: string | null,
    redemptions?: number | null,
    revenue?: number | null,
    spend?: number | null,
    topRewardId?: string | null,
    updatedAt: string,
  } | null,
};

export type GetRewardQueryVariables = {
  id: string,
};

export type GetRewardQuery = {
  getReward?:  {
    __typename: "Reward",
    availableRadius?: number | null,
    business?:  {
      __typename: "Business",
      address: string,
      billingType?: BusinessBillingType | null,
      businessType?: BusinessBusinessType | null,
      city: string,
      cpmRate?: number | null,
      createdAt: string,
      currentSpend?: number | null,
      description?: string | null,
      email: string,
      id: string,
      isActive?: boolean | null,
      isVerified?: boolean | null,
      latitude?: number | null,
      logoKey?: string | null,
      logoUrl?: string | null,
      longitude?: number | null,
      monthlyBudget?: number | null,
      name: string,
      owner: string,
      phone?: string | null,
      rejectionReason?: string | null,
      serviceRadius?: number | null,
      state: string,
      updatedAt: string,
      verificationStatus?: BusinessVerificationStatus | null,
      website?: string | null,
      zipCode: string,
    } | null,
    businessId: string,
    category?: RewardCategory | null,
    clicks?: number | null,
    createdAt: string,
    currentRedemptions?: number | null,
    dailyLimit?: number | null,
    daysOfWeek?: Array< string | null > | null,
    description: string,
    endDate?: string | null,
    id: string,
    imageKey?: string | null,
    imageUrl?: string | null,
    impressions?: number | null,
    isActive?: boolean | null,
    owner?: string | null,
    pointCost: number,
    redemptionInstructions?: string | null,
    redemptionRecords?:  {
      __typename: "ModelRewardRedemptionConnection",
      nextToken?: string | null,
    } | null,
    redemptionType?: RewardRedemptionType | null,
    redemptions?: number | null,
    retailValue?: number | null,
    rewardType?: RewardRewardType | null,
    startDate: string,
    status?: RewardStatus | null,
    targetAgeRanges?: Array< string | null > | null,
    targetFamilySizes?: Array< number | null > | null,
    termsAndConditions?: string | null,
    title: string,
    totalAvailable?: number | null,
    updatedAt: string,
  } | null,
};

export type GetRewardRedemptionQueryVariables = {
  id: string,
};

export type GetRewardRedemptionQuery = {
  getRewardRedemption?:  {
    __typename: "RewardRedemption",
    businessId?: string | null,
    businessRevenue?: number | null,
    childAge?: number | null,
    childId: string,
    createdAt: string,
    expiresAt?: string | null,
    familyId: string,
    fulfilledAt?: string | null,
    id: string,
    notes?: string | null,
    owner?: string | null,
    pointsSpent: number,
    redemptionCity?: string | null,
    redemptionCode?: string | null,
    redemptionDate?: string | null,
    redemptionStatus?: RewardRedemptionRedemptionStatus | null,
    redemptionZip?: string | null,
    reward?:  {
      __typename: "Reward",
      availableRadius?: number | null,
      businessId: string,
      category?: RewardCategory | null,
      clicks?: number | null,
      createdAt: string,
      currentRedemptions?: number | null,
      dailyLimit?: number | null,
      daysOfWeek?: Array< string | null > | null,
      description: string,
      endDate?: string | null,
      id: string,
      imageKey?: string | null,
      imageUrl?: string | null,
      impressions?: number | null,
      isActive?: boolean | null,
      owner?: string | null,
      pointCost: number,
      redemptionInstructions?: string | null,
      redemptionType?: RewardRedemptionType | null,
      redemptions?: number | null,
      retailValue?: number | null,
      rewardType?: RewardRewardType | null,
      startDate: string,
      status?: RewardStatus | null,
      targetAgeRanges?: Array< string | null > | null,
      targetFamilySizes?: Array< number | null > | null,
      termsAndConditions?: string | null,
      title: string,
      totalAvailable?: number | null,
      updatedAt: string,
    } | null,
    rewardId: string,
    updatedAt: string,
  } | null,
};

export type ListBusinessAnalyticsQueryVariables = {
  filter?: ModelBusinessAnalyticsFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListBusinessAnalyticsQuery = {
  listBusinessAnalytics?:  {
    __typename: "ModelBusinessAnalyticsConnection",
    items:  Array< {
      __typename: "BusinessAnalytics",
      avgChildAge?: number | null,
      businessId: string,
      clicks?: number | null,
      createdAt: string,
      date: string,
      id: string,
      impressions?: number | null,
      owner?: string | null,
      redemptions?: number | null,
      revenue?: number | null,
      spend?: number | null,
      topRewardId?: string | null,
      updatedAt: string,
    } | null >,
    nextToken?: string | null,
  } | null,
};

export type ListBusinessesQueryVariables = {
  filter?: ModelBusinessFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListBusinessesQuery = {
  listBusinesses?:  {
    __typename: "ModelBusinessConnection",
    items:  Array< {
      __typename: "Business",
      address: string,
      billingType?: BusinessBillingType | null,
      businessType?: BusinessBusinessType | null,
      city: string,
      cpmRate?: number | null,
      createdAt: string,
      currentSpend?: number | null,
      description?: string | null,
      email: string,
      id: string,
      isActive?: boolean | null,
      isVerified?: boolean | null,
      latitude?: number | null,
      logoKey?: string | null,
      logoUrl?: string | null,
      longitude?: number | null,
      monthlyBudget?: number | null,
      name: string,
      owner: string,
      phone?: string | null,
      rejectionReason?: string | null,
      serviceRadius?: number | null,
      state: string,
      updatedAt: string,
      verificationStatus?: BusinessVerificationStatus | null,
      website?: string | null,
      zipCode: string,
    } | null >,
    nextToken?: string | null,
  } | null,
};

export type ListRewardRedemptionsQueryVariables = {
  filter?: ModelRewardRedemptionFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListRewardRedemptionsQuery = {
  listRewardRedemptions?:  {
    __typename: "ModelRewardRedemptionConnection",
    items:  Array< {
      __typename: "RewardRedemption",
      businessId?: string | null,
      businessRevenue?: number | null,
      childAge?: number | null,
      childId: string,
      createdAt: string,
      expiresAt?: string | null,
      familyId: string,
      fulfilledAt?: string | null,
      id: string,
      notes?: string | null,
      owner?: string | null,
      pointsSpent: number,
      redemptionCity?: string | null,
      redemptionCode?: string | null,
      redemptionDate?: string | null,
      redemptionStatus?: RewardRedemptionRedemptionStatus | null,
      redemptionZip?: string | null,
      rewardId: string,
      updatedAt: string,
    } | null >,
    nextToken?: string | null,
  } | null,
};

export type ListRewardsQueryVariables = {
  filter?: ModelRewardFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListRewardsQuery = {
  listRewards?:  {
    __typename: "ModelRewardConnection",
    items:  Array< {
      __typename: "Reward",
      availableRadius?: number | null,
      businessId: string,
      category?: RewardCategory | null,
      clicks?: number | null,
      createdAt: string,
      currentRedemptions?: number | null,
      dailyLimit?: number | null,
      daysOfWeek?: Array< string | null > | null,
      description: string,
      endDate?: string | null,
      id: string,
      imageKey?: string | null,
      imageUrl?: string | null,
      impressions?: number | null,
      isActive?: boolean | null,
      owner?: string | null,
      pointCost: number,
      redemptionInstructions?: string | null,
      redemptionType?: RewardRedemptionType | null,
      redemptions?: number | null,
      retailValue?: number | null,
      rewardType?: RewardRewardType | null,
      startDate: string,
      status?: RewardStatus | null,
      targetAgeRanges?: Array< string | null > | null,
      targetFamilySizes?: Array< number | null > | null,
      termsAndConditions?: string | null,
      title: string,
      totalAvailable?: number | null,
      updatedAt: string,
    } | null >,
    nextToken?: string | null,
  } | null,
};

export type CreateBusinessMutationVariables = {
  condition?: ModelBusinessConditionInput | null,
  input: CreateBusinessInput,
};

export type CreateBusinessMutation = {
  createBusiness?:  {
    __typename: "Business",
    address: string,
    billingType?: BusinessBillingType | null,
    businessType?: BusinessBusinessType | null,
    city: string,
    cpmRate?: number | null,
    createdAt: string,
    currentSpend?: number | null,
    description?: string | null,
    email: string,
    id: string,
    isActive?: boolean | null,
    isVerified?: boolean | null,
    latitude?: number | null,
    logoKey?: string | null,
    logoUrl?: string | null,
    longitude?: number | null,
    monthlyBudget?: number | null,
    name: string,
    owner: string,
    phone?: string | null,
    rejectionReason?: string | null,
    rewards?:  {
      __typename: "ModelRewardConnection",
      nextToken?: string | null,
    } | null,
    serviceRadius?: number | null,
    state: string,
    updatedAt: string,
    verificationStatus?: BusinessVerificationStatus | null,
    website?: string | null,
    zipCode: string,
  } | null,
};

export type CreateBusinessAnalyticsMutationVariables = {
  condition?: ModelBusinessAnalyticsConditionInput | null,
  input: CreateBusinessAnalyticsInput,
};

export type CreateBusinessAnalyticsMutation = {
  createBusinessAnalytics?:  {
    __typename: "BusinessAnalytics",
    avgChildAge?: number | null,
    businessId: string,
    clicks?: number | null,
    createdAt: string,
    date: string,
    id: string,
    impressions?: number | null,
    owner?: string | null,
    redemptions?: number | null,
    revenue?: number | null,
    spend?: number | null,
    topRewardId?: string | null,
    updatedAt: string,
  } | null,
};

export type CreateRewardMutationVariables = {
  condition?: ModelRewardConditionInput | null,
  input: CreateRewardInput,
};

export type CreateRewardMutation = {
  createReward?:  {
    __typename: "Reward",
    availableRadius?: number | null,
    business?:  {
      __typename: "Business",
      address: string,
      billingType?: BusinessBillingType | null,
      businessType?: BusinessBusinessType | null,
      city: string,
      cpmRate?: number | null,
      createdAt: string,
      currentSpend?: number | null,
      description?: string | null,
      email: string,
      id: string,
      isActive?: boolean | null,
      isVerified?: boolean | null,
      latitude?: number | null,
      logoKey?: string | null,
      logoUrl?: string | null,
      longitude?: number | null,
      monthlyBudget?: number | null,
      name: string,
      owner: string,
      phone?: string | null,
      rejectionReason?: string | null,
      serviceRadius?: number | null,
      state: string,
      updatedAt: string,
      verificationStatus?: BusinessVerificationStatus | null,
      website?: string | null,
      zipCode: string,
    } | null,
    businessId: string,
    category?: RewardCategory | null,
    clicks?: number | null,
    createdAt: string,
    currentRedemptions?: number | null,
    dailyLimit?: number | null,
    daysOfWeek?: Array< string | null > | null,
    description: string,
    endDate?: string | null,
    id: string,
    imageKey?: string | null,
    imageUrl?: string | null,
    impressions?: number | null,
    isActive?: boolean | null,
    owner?: string | null,
    pointCost: number,
    redemptionInstructions?: string | null,
    redemptionRecords?:  {
      __typename: "ModelRewardRedemptionConnection",
      nextToken?: string | null,
    } | null,
    redemptionType?: RewardRedemptionType | null,
    redemptions?: number | null,
    retailValue?: number | null,
    rewardType?: RewardRewardType | null,
    startDate: string,
    status?: RewardStatus | null,
    targetAgeRanges?: Array< string | null > | null,
    targetFamilySizes?: Array< number | null > | null,
    termsAndConditions?: string | null,
    title: string,
    totalAvailable?: number | null,
    updatedAt: string,
  } | null,
};

export type CreateRewardRedemptionMutationVariables = {
  condition?: ModelRewardRedemptionConditionInput | null,
  input: CreateRewardRedemptionInput,
};

export type CreateRewardRedemptionMutation = {
  createRewardRedemption?:  {
    __typename: "RewardRedemption",
    businessId?: string | null,
    businessRevenue?: number | null,
    childAge?: number | null,
    childId: string,
    createdAt: string,
    expiresAt?: string | null,
    familyId: string,
    fulfilledAt?: string | null,
    id: string,
    notes?: string | null,
    owner?: string | null,
    pointsSpent: number,
    redemptionCity?: string | null,
    redemptionCode?: string | null,
    redemptionDate?: string | null,
    redemptionStatus?: RewardRedemptionRedemptionStatus | null,
    redemptionZip?: string | null,
    reward?:  {
      __typename: "Reward",
      availableRadius?: number | null,
      businessId: string,
      category?: RewardCategory | null,
      clicks?: number | null,
      createdAt: string,
      currentRedemptions?: number | null,
      dailyLimit?: number | null,
      daysOfWeek?: Array< string | null > | null,
      description: string,
      endDate?: string | null,
      id: string,
      imageKey?: string | null,
      imageUrl?: string | null,
      impressions?: number | null,
      isActive?: boolean | null,
      owner?: string | null,
      pointCost: number,
      redemptionInstructions?: string | null,
      redemptionType?: RewardRedemptionType | null,
      redemptions?: number | null,
      retailValue?: number | null,
      rewardType?: RewardRewardType | null,
      startDate: string,
      status?: RewardStatus | null,
      targetAgeRanges?: Array< string | null > | null,
      targetFamilySizes?: Array< number | null > | null,
      termsAndConditions?: string | null,
      title: string,
      totalAvailable?: number | null,
      updatedAt: string,
    } | null,
    rewardId: string,
    updatedAt: string,
  } | null,
};

export type DeleteBusinessMutationVariables = {
  condition?: ModelBusinessConditionInput | null,
  input: DeleteBusinessInput,
};

export type DeleteBusinessMutation = {
  deleteBusiness?:  {
    __typename: "Business",
    address: string,
    billingType?: BusinessBillingType | null,
    businessType?: BusinessBusinessType | null,
    city: string,
    cpmRate?: number | null,
    createdAt: string,
    currentSpend?: number | null,
    description?: string | null,
    email: string,
    id: string,
    isActive?: boolean | null,
    isVerified?: boolean | null,
    latitude?: number | null,
    logoKey?: string | null,
    logoUrl?: string | null,
    longitude?: number | null,
    monthlyBudget?: number | null,
    name: string,
    owner: string,
    phone?: string | null,
    rejectionReason?: string | null,
    rewards?:  {
      __typename: "ModelRewardConnection",
      nextToken?: string | null,
    } | null,
    serviceRadius?: number | null,
    state: string,
    updatedAt: string,
    verificationStatus?: BusinessVerificationStatus | null,
    website?: string | null,
    zipCode: string,
  } | null,
};

export type DeleteBusinessAnalyticsMutationVariables = {
  condition?: ModelBusinessAnalyticsConditionInput | null,
  input: DeleteBusinessAnalyticsInput,
};

export type DeleteBusinessAnalyticsMutation = {
  deleteBusinessAnalytics?:  {
    __typename: "BusinessAnalytics",
    avgChildAge?: number | null,
    businessId: string,
    clicks?: number | null,
    createdAt: string,
    date: string,
    id: string,
    impressions?: number | null,
    owner?: string | null,
    redemptions?: number | null,
    revenue?: number | null,
    spend?: number | null,
    topRewardId?: string | null,
    updatedAt: string,
  } | null,
};

export type DeleteRewardMutationVariables = {
  condition?: ModelRewardConditionInput | null,
  input: DeleteRewardInput,
};

export type DeleteRewardMutation = {
  deleteReward?:  {
    __typename: "Reward",
    availableRadius?: number | null,
    business?:  {
      __typename: "Business",
      address: string,
      billingType?: BusinessBillingType | null,
      businessType?: BusinessBusinessType | null,
      city: string,
      cpmRate?: number | null,
      createdAt: string,
      currentSpend?: number | null,
      description?: string | null,
      email: string,
      id: string,
      isActive?: boolean | null,
      isVerified?: boolean | null,
      latitude?: number | null,
      logoKey?: string | null,
      logoUrl?: string | null,
      longitude?: number | null,
      monthlyBudget?: number | null,
      name: string,
      owner: string,
      phone?: string | null,
      rejectionReason?: string | null,
      serviceRadius?: number | null,
      state: string,
      updatedAt: string,
      verificationStatus?: BusinessVerificationStatus | null,
      website?: string | null,
      zipCode: string,
    } | null,
    businessId: string,
    category?: RewardCategory | null,
    clicks?: number | null,
    createdAt: string,
    currentRedemptions?: number | null,
    dailyLimit?: number | null,
    daysOfWeek?: Array< string | null > | null,
    description: string,
    endDate?: string | null,
    id: string,
    imageKey?: string | null,
    imageUrl?: string | null,
    impressions?: number | null,
    isActive?: boolean | null,
    owner?: string | null,
    pointCost: number,
    redemptionInstructions?: string | null,
    redemptionRecords?:  {
      __typename: "ModelRewardRedemptionConnection",
      nextToken?: string | null,
    } | null,
    redemptionType?: RewardRedemptionType | null,
    redemptions?: number | null,
    retailValue?: number | null,
    rewardType?: RewardRewardType | null,
    startDate: string,
    status?: RewardStatus | null,
    targetAgeRanges?: Array< string | null > | null,
    targetFamilySizes?: Array< number | null > | null,
    termsAndConditions?: string | null,
    title: string,
    totalAvailable?: number | null,
    updatedAt: string,
  } | null,
};

export type DeleteRewardRedemptionMutationVariables = {
  condition?: ModelRewardRedemptionConditionInput | null,
  input: DeleteRewardRedemptionInput,
};

export type DeleteRewardRedemptionMutation = {
  deleteRewardRedemption?:  {
    __typename: "RewardRedemption",
    businessId?: string | null,
    businessRevenue?: number | null,
    childAge?: number | null,
    childId: string,
    createdAt: string,
    expiresAt?: string | null,
    familyId: string,
    fulfilledAt?: string | null,
    id: string,
    notes?: string | null,
    owner?: string | null,
    pointsSpent: number,
    redemptionCity?: string | null,
    redemptionCode?: string | null,
    redemptionDate?: string | null,
    redemptionStatus?: RewardRedemptionRedemptionStatus | null,
    redemptionZip?: string | null,
    reward?:  {
      __typename: "Reward",
      availableRadius?: number | null,
      businessId: string,
      category?: RewardCategory | null,
      clicks?: number | null,
      createdAt: string,
      currentRedemptions?: number | null,
      dailyLimit?: number | null,
      daysOfWeek?: Array< string | null > | null,
      description: string,
      endDate?: string | null,
      id: string,
      imageKey?: string | null,
      imageUrl?: string | null,
      impressions?: number | null,
      isActive?: boolean | null,
      owner?: string | null,
      pointCost: number,
      redemptionInstructions?: string | null,
      redemptionType?: RewardRedemptionType | null,
      redemptions?: number | null,
      retailValue?: number | null,
      rewardType?: RewardRewardType | null,
      startDate: string,
      status?: RewardStatus | null,
      targetAgeRanges?: Array< string | null > | null,
      targetFamilySizes?: Array< number | null > | null,
      termsAndConditions?: string | null,
      title: string,
      totalAvailable?: number | null,
      updatedAt: string,
    } | null,
    rewardId: string,
    updatedAt: string,
  } | null,
};

export type UpdateBusinessMutationVariables = {
  condition?: ModelBusinessConditionInput | null,
  input: UpdateBusinessInput,
};

export type UpdateBusinessMutation = {
  updateBusiness?:  {
    __typename: "Business",
    address: string,
    billingType?: BusinessBillingType | null,
    businessType?: BusinessBusinessType | null,
    city: string,
    cpmRate?: number | null,
    createdAt: string,
    currentSpend?: number | null,
    description?: string | null,
    email: string,
    id: string,
    isActive?: boolean | null,
    isVerified?: boolean | null,
    latitude?: number | null,
    logoKey?: string | null,
    logoUrl?: string | null,
    longitude?: number | null,
    monthlyBudget?: number | null,
    name: string,
    owner: string,
    phone?: string | null,
    rejectionReason?: string | null,
    rewards?:  {
      __typename: "ModelRewardConnection",
      nextToken?: string | null,
    } | null,
    serviceRadius?: number | null,
    state: string,
    updatedAt: string,
    verificationStatus?: BusinessVerificationStatus | null,
    website?: string | null,
    zipCode: string,
  } | null,
};

export type UpdateBusinessAnalyticsMutationVariables = {
  condition?: ModelBusinessAnalyticsConditionInput | null,
  input: UpdateBusinessAnalyticsInput,
};

export type UpdateBusinessAnalyticsMutation = {
  updateBusinessAnalytics?:  {
    __typename: "BusinessAnalytics",
    avgChildAge?: number | null,
    businessId: string,
    clicks?: number | null,
    createdAt: string,
    date: string,
    id: string,
    impressions?: number | null,
    owner?: string | null,
    redemptions?: number | null,
    revenue?: number | null,
    spend?: number | null,
    topRewardId?: string | null,
    updatedAt: string,
  } | null,
};

export type UpdateRewardMutationVariables = {
  condition?: ModelRewardConditionInput | null,
  input: UpdateRewardInput,
};

export type UpdateRewardMutation = {
  updateReward?:  {
    __typename: "Reward",
    availableRadius?: number | null,
    business?:  {
      __typename: "Business",
      address: string,
      billingType?: BusinessBillingType | null,
      businessType?: BusinessBusinessType | null,
      city: string,
      cpmRate?: number | null,
      createdAt: string,
      currentSpend?: number | null,
      description?: string | null,
      email: string,
      id: string,
      isActive?: boolean | null,
      isVerified?: boolean | null,
      latitude?: number | null,
      logoKey?: string | null,
      logoUrl?: string | null,
      longitude?: number | null,
      monthlyBudget?: number | null,
      name: string,
      owner: string,
      phone?: string | null,
      rejectionReason?: string | null,
      serviceRadius?: number | null,
      state: string,
      updatedAt: string,
      verificationStatus?: BusinessVerificationStatus | null,
      website?: string | null,
      zipCode: string,
    } | null,
    businessId: string,
    category?: RewardCategory | null,
    clicks?: number | null,
    createdAt: string,
    currentRedemptions?: number | null,
    dailyLimit?: number | null,
    daysOfWeek?: Array< string | null > | null,
    description: string,
    endDate?: string | null,
    id: string,
    imageKey?: string | null,
    imageUrl?: string | null,
    impressions?: number | null,
    isActive?: boolean | null,
    owner?: string | null,
    pointCost: number,
    redemptionInstructions?: string | null,
    redemptionRecords?:  {
      __typename: "ModelRewardRedemptionConnection",
      nextToken?: string | null,
    } | null,
    redemptionType?: RewardRedemptionType | null,
    redemptions?: number | null,
    retailValue?: number | null,
    rewardType?: RewardRewardType | null,
    startDate: string,
    status?: RewardStatus | null,
    targetAgeRanges?: Array< string | null > | null,
    targetFamilySizes?: Array< number | null > | null,
    termsAndConditions?: string | null,
    title: string,
    totalAvailable?: number | null,
    updatedAt: string,
  } | null,
};

export type UpdateRewardRedemptionMutationVariables = {
  condition?: ModelRewardRedemptionConditionInput | null,
  input: UpdateRewardRedemptionInput,
};

export type UpdateRewardRedemptionMutation = {
  updateRewardRedemption?:  {
    __typename: "RewardRedemption",
    businessId?: string | null,
    businessRevenue?: number | null,
    childAge?: number | null,
    childId: string,
    createdAt: string,
    expiresAt?: string | null,
    familyId: string,
    fulfilledAt?: string | null,
    id: string,
    notes?: string | null,
    owner?: string | null,
    pointsSpent: number,
    redemptionCity?: string | null,
    redemptionCode?: string | null,
    redemptionDate?: string | null,
    redemptionStatus?: RewardRedemptionRedemptionStatus | null,
    redemptionZip?: string | null,
    reward?:  {
      __typename: "Reward",
      availableRadius?: number | null,
      businessId: string,
      category?: RewardCategory | null,
      clicks?: number | null,
      createdAt: string,
      currentRedemptions?: number | null,
      dailyLimit?: number | null,
      daysOfWeek?: Array< string | null > | null,
      description: string,
      endDate?: string | null,
      id: string,
      imageKey?: string | null,
      imageUrl?: string | null,
      impressions?: number | null,
      isActive?: boolean | null,
      owner?: string | null,
      pointCost: number,
      redemptionInstructions?: string | null,
      redemptionType?: RewardRedemptionType | null,
      redemptions?: number | null,
      retailValue?: number | null,
      rewardType?: RewardRewardType | null,
      startDate: string,
      status?: RewardStatus | null,
      targetAgeRanges?: Array< string | null > | null,
      targetFamilySizes?: Array< number | null > | null,
      termsAndConditions?: string | null,
      title: string,
      totalAvailable?: number | null,
      updatedAt: string,
    } | null,
    rewardId: string,
    updatedAt: string,
  } | null,
};

export type OnCreateBusinessSubscriptionVariables = {
  filter?: ModelSubscriptionBusinessFilterInput | null,
  owner?: string | null,
};

export type OnCreateBusinessSubscription = {
  onCreateBusiness?:  {
    __typename: "Business",
    address: string,
    billingType?: BusinessBillingType | null,
    businessType?: BusinessBusinessType | null,
    city: string,
    cpmRate?: number | null,
    createdAt: string,
    currentSpend?: number | null,
    description?: string | null,
    email: string,
    id: string,
    isActive?: boolean | null,
    isVerified?: boolean | null,
    latitude?: number | null,
    logoKey?: string | null,
    logoUrl?: string | null,
    longitude?: number | null,
    monthlyBudget?: number | null,
    name: string,
    owner: string,
    phone?: string | null,
    rejectionReason?: string | null,
    rewards?:  {
      __typename: "ModelRewardConnection",
      nextToken?: string | null,
    } | null,
    serviceRadius?: number | null,
    state: string,
    updatedAt: string,
    verificationStatus?: BusinessVerificationStatus | null,
    website?: string | null,
    zipCode: string,
  } | null,
};

export type OnCreateBusinessAnalyticsSubscriptionVariables = {
  filter?: ModelSubscriptionBusinessAnalyticsFilterInput | null,
  owner?: string | null,
};

export type OnCreateBusinessAnalyticsSubscription = {
  onCreateBusinessAnalytics?:  {
    __typename: "BusinessAnalytics",
    avgChildAge?: number | null,
    businessId: string,
    clicks?: number | null,
    createdAt: string,
    date: string,
    id: string,
    impressions?: number | null,
    owner?: string | null,
    redemptions?: number | null,
    revenue?: number | null,
    spend?: number | null,
    topRewardId?: string | null,
    updatedAt: string,
  } | null,
};

export type OnCreateRewardSubscriptionVariables = {
  filter?: ModelSubscriptionRewardFilterInput | null,
  owner?: string | null,
};

export type OnCreateRewardSubscription = {
  onCreateReward?:  {
    __typename: "Reward",
    availableRadius?: number | null,
    business?:  {
      __typename: "Business",
      address: string,
      billingType?: BusinessBillingType | null,
      businessType?: BusinessBusinessType | null,
      city: string,
      cpmRate?: number | null,
      createdAt: string,
      currentSpend?: number | null,
      description?: string | null,
      email: string,
      id: string,
      isActive?: boolean | null,
      isVerified?: boolean | null,
      latitude?: number | null,
      logoKey?: string | null,
      logoUrl?: string | null,
      longitude?: number | null,
      monthlyBudget?: number | null,
      name: string,
      owner: string,
      phone?: string | null,
      rejectionReason?: string | null,
      serviceRadius?: number | null,
      state: string,
      updatedAt: string,
      verificationStatus?: BusinessVerificationStatus | null,
      website?: string | null,
      zipCode: string,
    } | null,
    businessId: string,
    category?: RewardCategory | null,
    clicks?: number | null,
    createdAt: string,
    currentRedemptions?: number | null,
    dailyLimit?: number | null,
    daysOfWeek?: Array< string | null > | null,
    description: string,
    endDate?: string | null,
    id: string,
    imageKey?: string | null,
    imageUrl?: string | null,
    impressions?: number | null,
    isActive?: boolean | null,
    owner?: string | null,
    pointCost: number,
    redemptionInstructions?: string | null,
    redemptionRecords?:  {
      __typename: "ModelRewardRedemptionConnection",
      nextToken?: string | null,
    } | null,
    redemptionType?: RewardRedemptionType | null,
    redemptions?: number | null,
    retailValue?: number | null,
    rewardType?: RewardRewardType | null,
    startDate: string,
    status?: RewardStatus | null,
    targetAgeRanges?: Array< string | null > | null,
    targetFamilySizes?: Array< number | null > | null,
    termsAndConditions?: string | null,
    title: string,
    totalAvailable?: number | null,
    updatedAt: string,
  } | null,
};

export type OnCreateRewardRedemptionSubscriptionVariables = {
  filter?: ModelSubscriptionRewardRedemptionFilterInput | null,
  owner?: string | null,
};

export type OnCreateRewardRedemptionSubscription = {
  onCreateRewardRedemption?:  {
    __typename: "RewardRedemption",
    businessId?: string | null,
    businessRevenue?: number | null,
    childAge?: number | null,
    childId: string,
    createdAt: string,
    expiresAt?: string | null,
    familyId: string,
    fulfilledAt?: string | null,
    id: string,
    notes?: string | null,
    owner?: string | null,
    pointsSpent: number,
    redemptionCity?: string | null,
    redemptionCode?: string | null,
    redemptionDate?: string | null,
    redemptionStatus?: RewardRedemptionRedemptionStatus | null,
    redemptionZip?: string | null,
    reward?:  {
      __typename: "Reward",
      availableRadius?: number | null,
      businessId: string,
      category?: RewardCategory | null,
      clicks?: number | null,
      createdAt: string,
      currentRedemptions?: number | null,
      dailyLimit?: number | null,
      daysOfWeek?: Array< string | null > | null,
      description: string,
      endDate?: string | null,
      id: string,
      imageKey?: string | null,
      imageUrl?: string | null,
      impressions?: number | null,
      isActive?: boolean | null,
      owner?: string | null,
      pointCost: number,
      redemptionInstructions?: string | null,
      redemptionType?: RewardRedemptionType | null,
      redemptions?: number | null,
      retailValue?: number | null,
      rewardType?: RewardRewardType | null,
      startDate: string,
      status?: RewardStatus | null,
      targetAgeRanges?: Array< string | null > | null,
      targetFamilySizes?: Array< number | null > | null,
      termsAndConditions?: string | null,
      title: string,
      totalAvailable?: number | null,
      updatedAt: string,
    } | null,
    rewardId: string,
    updatedAt: string,
  } | null,
};

export type OnDeleteBusinessSubscriptionVariables = {
  filter?: ModelSubscriptionBusinessFilterInput | null,
  owner?: string | null,
};

export type OnDeleteBusinessSubscription = {
  onDeleteBusiness?:  {
    __typename: "Business",
    address: string,
    billingType?: BusinessBillingType | null,
    businessType?: BusinessBusinessType | null,
    city: string,
    cpmRate?: number | null,
    createdAt: string,
    currentSpend?: number | null,
    description?: string | null,
    email: string,
    id: string,
    isActive?: boolean | null,
    isVerified?: boolean | null,
    latitude?: number | null,
    logoKey?: string | null,
    logoUrl?: string | null,
    longitude?: number | null,
    monthlyBudget?: number | null,
    name: string,
    owner: string,
    phone?: string | null,
    rejectionReason?: string | null,
    rewards?:  {
      __typename: "ModelRewardConnection",
      nextToken?: string | null,
    } | null,
    serviceRadius?: number | null,
    state: string,
    updatedAt: string,
    verificationStatus?: BusinessVerificationStatus | null,
    website?: string | null,
    zipCode: string,
  } | null,
};

export type OnDeleteBusinessAnalyticsSubscriptionVariables = {
  filter?: ModelSubscriptionBusinessAnalyticsFilterInput | null,
  owner?: string | null,
};

export type OnDeleteBusinessAnalyticsSubscription = {
  onDeleteBusinessAnalytics?:  {
    __typename: "BusinessAnalytics",
    avgChildAge?: number | null,
    businessId: string,
    clicks?: number | null,
    createdAt: string,
    date: string,
    id: string,
    impressions?: number | null,
    owner?: string | null,
    redemptions?: number | null,
    revenue?: number | null,
    spend?: number | null,
    topRewardId?: string | null,
    updatedAt: string,
  } | null,
};

export type OnDeleteRewardSubscriptionVariables = {
  filter?: ModelSubscriptionRewardFilterInput | null,
  owner?: string | null,
};

export type OnDeleteRewardSubscription = {
  onDeleteReward?:  {
    __typename: "Reward",
    availableRadius?: number | null,
    business?:  {
      __typename: "Business",
      address: string,
      billingType?: BusinessBillingType | null,
      businessType?: BusinessBusinessType | null,
      city: string,
      cpmRate?: number | null,
      createdAt: string,
      currentSpend?: number | null,
      description?: string | null,
      email: string,
      id: string,
      isActive?: boolean | null,
      isVerified?: boolean | null,
      latitude?: number | null,
      logoKey?: string | null,
      logoUrl?: string | null,
      longitude?: number | null,
      monthlyBudget?: number | null,
      name: string,
      owner: string,
      phone?: string | null,
      rejectionReason?: string | null,
      serviceRadius?: number | null,
      state: string,
      updatedAt: string,
      verificationStatus?: BusinessVerificationStatus | null,
      website?: string | null,
      zipCode: string,
    } | null,
    businessId: string,
    category?: RewardCategory | null,
    clicks?: number | null,
    createdAt: string,
    currentRedemptions?: number | null,
    dailyLimit?: number | null,
    daysOfWeek?: Array< string | null > | null,
    description: string,
    endDate?: string | null,
    id: string,
    imageKey?: string | null,
    imageUrl?: string | null,
    impressions?: number | null,
    isActive?: boolean | null,
    owner?: string | null,
    pointCost: number,
    redemptionInstructions?: string | null,
    redemptionRecords?:  {
      __typename: "ModelRewardRedemptionConnection",
      nextToken?: string | null,
    } | null,
    redemptionType?: RewardRedemptionType | null,
    redemptions?: number | null,
    retailValue?: number | null,
    rewardType?: RewardRewardType | null,
    startDate: string,
    status?: RewardStatus | null,
    targetAgeRanges?: Array< string | null > | null,
    targetFamilySizes?: Array< number | null > | null,
    termsAndConditions?: string | null,
    title: string,
    totalAvailable?: number | null,
    updatedAt: string,
  } | null,
};

export type OnDeleteRewardRedemptionSubscriptionVariables = {
  filter?: ModelSubscriptionRewardRedemptionFilterInput | null,
  owner?: string | null,
};

export type OnDeleteRewardRedemptionSubscription = {
  onDeleteRewardRedemption?:  {
    __typename: "RewardRedemption",
    businessId?: string | null,
    businessRevenue?: number | null,
    childAge?: number | null,
    childId: string,
    createdAt: string,
    expiresAt?: string | null,
    familyId: string,
    fulfilledAt?: string | null,
    id: string,
    notes?: string | null,
    owner?: string | null,
    pointsSpent: number,
    redemptionCity?: string | null,
    redemptionCode?: string | null,
    redemptionDate?: string | null,
    redemptionStatus?: RewardRedemptionRedemptionStatus | null,
    redemptionZip?: string | null,
    reward?:  {
      __typename: "Reward",
      availableRadius?: number | null,
      businessId: string,
      category?: RewardCategory | null,
      clicks?: number | null,
      createdAt: string,
      currentRedemptions?: number | null,
      dailyLimit?: number | null,
      daysOfWeek?: Array< string | null > | null,
      description: string,
      endDate?: string | null,
      id: string,
      imageKey?: string | null,
      imageUrl?: string | null,
      impressions?: number | null,
      isActive?: boolean | null,
      owner?: string | null,
      pointCost: number,
      redemptionInstructions?: string | null,
      redemptionType?: RewardRedemptionType | null,
      redemptions?: number | null,
      retailValue?: number | null,
      rewardType?: RewardRewardType | null,
      startDate: string,
      status?: RewardStatus | null,
      targetAgeRanges?: Array< string | null > | null,
      targetFamilySizes?: Array< number | null > | null,
      termsAndConditions?: string | null,
      title: string,
      totalAvailable?: number | null,
      updatedAt: string,
    } | null,
    rewardId: string,
    updatedAt: string,
  } | null,
};

export type OnUpdateBusinessSubscriptionVariables = {
  filter?: ModelSubscriptionBusinessFilterInput | null,
  owner?: string | null,
};

export type OnUpdateBusinessSubscription = {
  onUpdateBusiness?:  {
    __typename: "Business",
    address: string,
    billingType?: BusinessBillingType | null,
    businessType?: BusinessBusinessType | null,
    city: string,
    cpmRate?: number | null,
    createdAt: string,
    currentSpend?: number | null,
    description?: string | null,
    email: string,
    id: string,
    isActive?: boolean | null,
    isVerified?: boolean | null,
    latitude?: number | null,
    logoKey?: string | null,
    logoUrl?: string | null,
    longitude?: number | null,
    monthlyBudget?: number | null,
    name: string,
    owner: string,
    phone?: string | null,
    rejectionReason?: string | null,
    rewards?:  {
      __typename: "ModelRewardConnection",
      nextToken?: string | null,
    } | null,
    serviceRadius?: number | null,
    state: string,
    updatedAt: string,
    verificationStatus?: BusinessVerificationStatus | null,
    website?: string | null,
    zipCode: string,
  } | null,
};

export type OnUpdateBusinessAnalyticsSubscriptionVariables = {
  filter?: ModelSubscriptionBusinessAnalyticsFilterInput | null,
  owner?: string | null,
};

export type OnUpdateBusinessAnalyticsSubscription = {
  onUpdateBusinessAnalytics?:  {
    __typename: "BusinessAnalytics",
    avgChildAge?: number | null,
    businessId: string,
    clicks?: number | null,
    createdAt: string,
    date: string,
    id: string,
    impressions?: number | null,
    owner?: string | null,
    redemptions?: number | null,
    revenue?: number | null,
    spend?: number | null,
    topRewardId?: string | null,
    updatedAt: string,
  } | null,
};

export type OnUpdateRewardSubscriptionVariables = {
  filter?: ModelSubscriptionRewardFilterInput | null,
  owner?: string | null,
};

export type OnUpdateRewardSubscription = {
  onUpdateReward?:  {
    __typename: "Reward",
    availableRadius?: number | null,
    business?:  {
      __typename: "Business",
      address: string,
      billingType?: BusinessBillingType | null,
      businessType?: BusinessBusinessType | null,
      city: string,
      cpmRate?: number | null,
      createdAt: string,
      currentSpend?: number | null,
      description?: string | null,
      email: string,
      id: string,
      isActive?: boolean | null,
      isVerified?: boolean | null,
      latitude?: number | null,
      logoKey?: string | null,
      logoUrl?: string | null,
      longitude?: number | null,
      monthlyBudget?: number | null,
      name: string,
      owner: string,
      phone?: string | null,
      rejectionReason?: string | null,
      serviceRadius?: number | null,
      state: string,
      updatedAt: string,
      verificationStatus?: BusinessVerificationStatus | null,
      website?: string | null,
      zipCode: string,
    } | null,
    businessId: string,
    category?: RewardCategory | null,
    clicks?: number | null,
    createdAt: string,
    currentRedemptions?: number | null,
    dailyLimit?: number | null,
    daysOfWeek?: Array< string | null > | null,
    description: string,
    endDate?: string | null,
    id: string,
    imageKey?: string | null,
    imageUrl?: string | null,
    impressions?: number | null,
    isActive?: boolean | null,
    owner?: string | null,
    pointCost: number,
    redemptionInstructions?: string | null,
    redemptionRecords?:  {
      __typename: "ModelRewardRedemptionConnection",
      nextToken?: string | null,
    } | null,
    redemptionType?: RewardRedemptionType | null,
    redemptions?: number | null,
    retailValue?: number | null,
    rewardType?: RewardRewardType | null,
    startDate: string,
    status?: RewardStatus | null,
    targetAgeRanges?: Array< string | null > | null,
    targetFamilySizes?: Array< number | null > | null,
    termsAndConditions?: string | null,
    title: string,
    totalAvailable?: number | null,
    updatedAt: string,
  } | null,
};

export type OnUpdateRewardRedemptionSubscriptionVariables = {
  filter?: ModelSubscriptionRewardRedemptionFilterInput | null,
  owner?: string | null,
};

export type OnUpdateRewardRedemptionSubscription = {
  onUpdateRewardRedemption?:  {
    __typename: "RewardRedemption",
    businessId?: string | null,
    businessRevenue?: number | null,
    childAge?: number | null,
    childId: string,
    createdAt: string,
    expiresAt?: string | null,
    familyId: string,
    fulfilledAt?: string | null,
    id: string,
    notes?: string | null,
    owner?: string | null,
    pointsSpent: number,
    redemptionCity?: string | null,
    redemptionCode?: string | null,
    redemptionDate?: string | null,
    redemptionStatus?: RewardRedemptionRedemptionStatus | null,
    redemptionZip?: string | null,
    reward?:  {
      __typename: "Reward",
      availableRadius?: number | null,
      businessId: string,
      category?: RewardCategory | null,
      clicks?: number | null,
      createdAt: string,
      currentRedemptions?: number | null,
      dailyLimit?: number | null,
      daysOfWeek?: Array< string | null > | null,
      description: string,
      endDate?: string | null,
      id: string,
      imageKey?: string | null,
      imageUrl?: string | null,
      impressions?: number | null,
      isActive?: boolean | null,
      owner?: string | null,
      pointCost: number,
      redemptionInstructions?: string | null,
      redemptionType?: RewardRedemptionType | null,
      redemptions?: number | null,
      retailValue?: number | null,
      rewardType?: RewardRewardType | null,
      startDate: string,
      status?: RewardStatus | null,
      targetAgeRanges?: Array< string | null > | null,
      targetFamilySizes?: Array< number | null > | null,
      termsAndConditions?: string | null,
      title: string,
      totalAvailable?: number | null,
      updatedAt: string,
    } | null,
    rewardId: string,
    updatedAt: string,
  } | null,
};
